export const LOADING_SUCCESS_WATCHES="LOADING_SUCCESS_WATCHES"
export const LOADING_SUCCESS_SOCKS="LOADING_SUCCESS_SOCKS"
export const LOADING_SUCCESS_SPORTMATS="LOADING_SUCCESS_SPORTSMATS"
export const LOADING_SUCCESS_HATS="LOADING_SUCCESS_HATS"
export const LOADING_SUCCESS_BAGS = "LOADING_SUCCESS_BAGS";
export const LOADING_SUCCESS_ALL_ACCESSORIES = "LOADING_SUCCESS_ALL_ACCESSORIES";

export const IS_LOADING_WATCHES="IS_LOADING_WATCHES"
export const IS_LOADING_SOCKS="IS_LOADING_SOCKS"
export const IS_LOADING_SPORTMATS="IS_LOADING_SPORTMATS"
export const IS_LOADING_HATS="IS_LOADING_HATS"
export const IS_LOADING_BAGS = "IS_LOADING_BAGS";
export const IS_LOADING_ALL_ACCESSORIES = "IS_LOADING_ALL_ACCESSORIES";


export const LOADING_ERROR_WATCHES = "LOADING_ERROR_WATCHES";
export const LOADING_ERROR_SOCKS = "LOADING_ERROR_SOCKS";
export const LOADING_ERROR_SPORTMATS = "LOADING_ERROR_SPORTSMATS";
export const LOADING_ERROR_HATS = "LOADING_ERROR_HATS";
export const LOADING_ERROR_BAGS = "LOADING_ERROR_BAGS";
export const LOADING_ERROR_ALL_ACCESSORIES = "LOADING_ERROR_ALL_ACCESSORIES";