export const LOADING_SUCCESS_PANTS="LOADING_SUCCESS_PANTS"
export const LOADING_SUCCESS_SHORTS="LOADING_SUCCESS_SHORTS"
export const LOADING_SUCCESS_SWEATSHIRTS="LOADING_SUCCESS_SWEATSHIRTS"
export const LOADING_SUCCESS_TSHIRTS="LOADING_SUCCESS_TSHIRTS"
export const LOADING_SUCCESS_TOP="LOADING_SUCCESS_TOP"
export const LOADING_SUCCESS_JERSEY="LOADING_SUCCESS_JERSEY"
export const LOADING_SUCCESS_ALL_CLOTHES = "LOADING_SUCCESS_ALL_CLOTHES";

export const IS_LOADING_PANTS="IS_LOADING_PANTS"
export const IS_LOADING_SHORTS="IS_LOADING_SHORTS"
export const IS_LOADING_SWEATSHIRTS="IS_LOADING_SWEATSHIRTS"
export const IS_LOADING_TSHIRTS="IS_LOADING_TSHIRTS"
export const IS_LOADING_TOP="IS_LOADING_TOP"
export const IS_LOADING_JERSEY="IS_LOADING_JERSEY"
export const IS_LOADING_ALL_CLOTHES = "IS_LOADING_ALL_CLOTHES"

export const LOADING_ERROR_PANTS="LOADING_ERROR_PANTS"
export const LOADING_ERROR_SHORTS="LOADING_ERROR_SHORTS"
export const LOADING_ERROR_SWEATSHIRTS="LOADING_ERROR_SWEATSHIRTS"
export const LOADING_ERROR_TSHIRTS="LOADING_ERROR_TSHIRTS"
export const LOADING_ERROR_TOP="LOADING_ERROR_TOP"
export const LOADING_ERROR_JERSEY="LOADING_ERROR_JERSEY"
export const LOADING_ERROR_ALL_CLOTHES = "LOADING_ERROR_ALL_CLOTHES";

