export const LOADING_SUCCESS_LIFESTYLE="LOADING_SUCCESS_LIFESTYLE";
export const LOADING_SUCCESS_TENNIS="LOADING_SUCCESS_TENNIS";
export const LOADING_SUCCESS_BASKET="LOADING_SUCCESS_BASKET";
export const LOADING_SUCCESS_FOOT="LOADING_SUCCESS_FOOT";
export const LOADING_SUCCESS_ALL_SHOES="LOADING_SUCCESS_ALL_SHOES";
// export const LOADING_SUCCESS_MEN="LOADING_SUCCESS_MEN";
// export const LOADING_SUCCESS_WOMEN="LOADING_SUCCESS_WOMEN";
// export const LOADING_SUCCESS_CHILDREN="LOADING_SUCCESS_CHILDREN";

export const IS_LOADING="IS_LOADING";
export const IS_LOADING_LIFESTYLE="IS_LOADING_LIFESTYLE";
export const IS_LOADING_TENNIS="IS_LOADING_TENNIS";
export const IS_LOADING_BASKET="IS_LOADING_BASKET";
export const IS_LOADING_MEN="IS_LOADING_MEN";
export const IS_LOADING_FOOT="IS_LOADING_FOOT";
export const IS_LOADING_ALL_SHOES="IS_LOADING_ALL_SHOES";
export const IS_LOADING_WOMEN="IS_LOADING_WOMEN";
export const IS_LOADING_CHILDREN="IS_LOADING_CHILDREN";

export const LOADING_ERROR_LIFESTYLE="LOADING_ERROR_LIFESTYLE";
export const LOADING_ERROR_TENNIS="LOADING_ERROR_TENNIS";
export const LOADING_ERROR_BASKET="LOADING_ERROR_BASKET";
export const LOADING_ERROR_FOOT="LOADING_ERROR_FOOT";
export const LOADING_ERROR_ALL_SHOES="LOADING_ERROR_ALL_SHOES";
export const LOADING_ERROR_MEN="LOADING_ERROR_MEN";
export const LOADING_ERROR_WOMEN="LOADING_ERROR_WOMEN";
export const LOADING_ERROR_CHILDREN="LOADING_ERROR_CHILDREN";
